url: 'https://gathuku.me'
baseurl: ''
title: 'Moses Gathuku site'
tagline: Bloging my day to day experience with Ruby and Rails
author: Moses Gathuku
twitter:
  username: Gathukumose
  card: summary_large_image
logo: /assets/images/avatar.png
social:
  name: Moses Gathuku
  links:
    - 'https://twitter.com/Gathukumose'
    - 'https://github.com/gathuku'

plugins:
  - jekyll-postcss
  - jekyll-seo-tag

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
